//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.Buro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.Buro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_pkg_advice {
            get {
                object obj = ResourceManager.GetObject("buro_pkg_advice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_pkg_floor {
            get {
                object obj = ResourceManager.GetObject("buro_pkg_floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_pkg_iteration {
            get {
                object obj = ResourceManager.GetObject("buro_pkg_iteration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_pkg_program {
            get {
                object obj = ResourceManager.GetObject("buro_pkg_program", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_pkg_testfit {
            get {
                object obj = ResourceManager.GetObject("buro_pkg_testfit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_advice {
            get {
                object obj = ResourceManager.GetObject("buro_read_advice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_program {
            get {
                object obj = ResourceManager.GetObject("buro_read_program", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_program_manifest {
            get {
                object obj = ResourceManager.GetObject("buro_read_program_manifest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_room {
            get {
                object obj = ResourceManager.GetObject("buro_read_room", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_zone {
            get {
                object obj = ResourceManager.GetObject("buro_read_zone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_read_zone_manifest {
            get {
                object obj = ResourceManager.GetObject("buro_read_zone_manifest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buro_solve {
            get {
                object obj = ResourceManager.GetObject("buro_solve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Category_Debug {
            get {
                return ResourceManager.GetString("Category_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch.
        /// </summary>
        internal static string Category_Dispatch {
            get {
                return ResourceManager.GetString("Category_Dispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buro.
        /// </summary>
        internal static string Category_Main {
            get {
                return ResourceManager.GetString("Category_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string Category_Packages {
            get {
                return ResourceManager.GetString("Category_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output room package geometry and statistics..
        /// </summary>
        internal static string GetRooms_Desc {
            get {
                return ResourceManager.GetString("GetRooms_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadRoomPackage.
        /// </summary>
        internal static string GetRooms_Label {
            get {
                return ResourceManager.GetString("GetRooms_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Room Package.
        /// </summary>
        internal static string GetRooms_Name {
            get {
                return ResourceManager.GetString("GetRooms_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Rhino data into a floor plan terrain formatted for Office Manager..
        /// </summary>
        internal static string PackageFloorPlan_Desc {
            get {
                return ResourceManager.GetString("PackageFloorPlan_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads and combines solution data with advice..
        /// </summary>
        internal static string PackageIteration_Desc {
            get {
                return ResourceManager.GetString("PackageIteration_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration.
        /// </summary>
        internal static string PackageIteration_Label {
            get {
                return ResourceManager.GetString("PackageIteration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Iteraction.
        /// </summary>
        internal static string PackageIteration_Name {
            get {
                return ResourceManager.GetString("PackageIteration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output advice package geometry..
        /// </summary>
        internal static string ReadAdvice_Desc {
            get {
                return ResourceManager.GetString("ReadAdvice_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadAdvice.
        /// </summary>
        internal static string ReadAdvice_Label {
            get {
                return ResourceManager.GetString("ReadAdvice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Advice.
        /// </summary>
        internal static string ReadAdvice_Name {
            get {
                return ResourceManager.GetString("ReadAdvice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse test fit package and output solutions..
        /// </summary>
        internal static string Solver_Desc {
            get {
                return ResourceManager.GetString("Solver_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solver.
        /// </summary>
        internal static string Solver_Label {
            get {
                return ResourceManager.GetString("Solver_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solver.
        /// </summary>
        internal static string Solver_Name {
            get {
                return ResourceManager.GetString("Solver_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buro.
        /// </summary>
        internal static string TabName {
            get {
                return ResourceManager.GetString("TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats user-input adjustments for interpretation..
        /// </summary>
        internal static string WriteAdvice_Desc {
            get {
                return ResourceManager.GetString("WriteAdvice_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteAdvice.
        /// </summary>
        internal static string WriteAdvice_Label {
            get {
                return ResourceManager.GetString("WriteAdvice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Advice.
        /// </summary>
        internal static string WriteAdvice_Name {
            get {
                return ResourceManager.GetString("WriteAdvice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats solution geometry and evaluation data for interpretation..
        /// </summary>
        internal static string WriteSolution_Desc {
            get {
                return ResourceManager.GetString("WriteSolution_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteSolution.
        /// </summary>
        internal static string WriteSolution_Label {
            get {
                return ResourceManager.GetString("WriteSolution_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Solution.
        /// </summary>
        internal static string WriteSolution_Name {
            get {
                return ResourceManager.GetString("WriteSolution_Name", resourceCulture);
            }
        }
    }
}
